#!/bin/bash
echo "============================================"
echo "推送 Zhang Lab 网站到 GitHub"
echo "============================================"
echo ""
echo "你需要一个GitHub Personal Access Token"
echo "如果还没有，请按以下步骤获取："
echo ""
echo "1. 在浏览器打开: https://github.com/settings/tokens/new"
echo "2. 填写信息："
echo "   Note: Lab Website"
echo "   Expiration: 选择 'No expiration' 或 '90 days'"
echo "   勾选: ☑ repo (勾选整个repo权限)"
echo "3. 点击绿色按钮 'Generate token'"
echo "4. 复制生成的token (以ghp_开头的长字符串)"
echo ""
read -p "按回车键继续推送..."
echo ""
echo "正在推送到 GitHub..."
git push -u origin main
